### ISSUE TITLE
С++20 deprecated error

### ISSUE THREAD

**Issue by Receiver1** [vladp72/hcrypt#2]
Compiler version: MSVC v143
C++ Language Standard: C++20
Problem: I get error `C4996: 'std::is_pod_v<unsigned long>': was declared deprecated` when I try to compile the project on this build. Problematic `line 773`, located in the `hbcrypt.hpp file`. Either add a check for the compiler version and replace it with `std::is_pod<T>{} == (std::is_trivial<T>{} && std::is_standard_layout<T>{})`, or delete this assert

**Comment by vladp72** [comment]
Thank you for your feedback. I took your suggestion and replaced is_pod with is_trivial && is_standard_layout.
Issue is addressed by https://github.com/vladp72/hcrypt/commit/b6843fa2831e76e1544a7654006dc0e4e57634a6,
