### ISSUE TITLE
How to use hcrypt::from_hex?

### ISSUE THREAD

**Issue by jungjin09** [vladp72/hcrypt#4]
```
unsigned char const key[] = {
	0x1b, 0x20, 0x5a, 0x9e, 0x2b, 0xe3, 0xfe, 0x85, 0x9c, 0x37, 0xf1,
	0xaf, 0xfe, 0x81, 0x88, 0x92, 0x9c, 0x37, 0xf1, 0xaf, 0xfe, 0x81,
	0x88, 0x92, 0x9c, 0x37, 0xf1, 0xaf, 0xfe, 0x81, 0x88, 0x92,
};

try {
	bcrypt::algorithm_provider ap{ BCRYPT_AES_ALGORITHM };
	ap.set_chaining_mode(BCRYPT_CHAIN_MODE_CCM);

	bcrypt::key k{ ap.generate_symmetric_key(
				  reinterpret_cast<char const*>(key),
				  32) };

	std::string_view aad("Not so secret additionally authenticated data");

	UCHAR iv[12] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 0xa, 0xb, 0xc };
	UCHAR tag[16] = { 0 };

	BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO aadInfo;
	BCRYPT_INIT_AUTH_MODE_INFO(aadInfo);
	aadInfo.pbNonce = iv;
	aadInfo.cbNonce = sizeof(iv);
	aadInfo.pbAuthData = reinterpret_cast<UCHAR*>(const_cast<char*>(&aad[0]));
	aadInfo.cbAuthData = static_cast<ULONG>(aad.size());
	aadInfo.cbAAD = static_cast<ULONG>(aad.size());
	aadInfo.pbTag = tag;
	aadInfo.cbTag = sizeof(tag);

	size_t bytes_written{ 0 };
	k.encrypt(nullptr, 0, &aadInfo, nullptr, 0, nullptr, 0, &bytes_written);
	auto t = hcrypt::to_hex(std::begin(tag), std::end(tag));


        /////////////////////////////////
	**auto ta=hcrypt::from_hex(???);**
        ...
```
Hi,
    The parameters you use may seem a bit confusing to someone not versed in c++.
![image](https://github.com/vladp72/hcrypt/assets/99936463/383880d3-670e-4823-8254-d56ec1f74487)
	
    Is it possible to reproduce a more readable function for example:
```
    string encrypt(string plaintext, string key);
    string decrypt(string code, string key);
```
    I think that would be much more accessible.
Thanks you!

**Comment by vladp72** [comment]
Hello @dangdkhanh. I appreciate your feedback. Can you please help me to understand your ask. There are two overloads of to_hex in https://github.com/vladp72/hcrypt/blob/master/include/hcrypt_common.hpp. 

One takes iterators and returns a string:

   template<typename I>
    inline std::wstring to_hex(I begin, I const end, size_t group_size = 0, wchar_t group_separator = L' ') 

and another takes a container, gets iterators from the container and returns a string:

    template<typename C>
    inline std::wstring to_hex(C const &c, size_t group_size = 0, wchar_t group_separator = L' ') {
        std::wstring result;
        to_hex(std::begin(c), std::end(c), group_size, group_separator, &result);
        return result;
    }

Is not the second overload what you are asking for?

**Comment by vladp72** [comment]
Resolving. Please let me know if you have further question.
